### ISSUE TITLE
Duo administrator/authentication logs

### ISSUE THREAD

**Issue by grimmthetallest** [criblio/collector-templates#1]
This collector template would be very helpful to have - there was [at least one discussion](https://community.cribl.io/discussion/257/how-can-i-create-a-rest-collection-with-authentication-requiring-an-hmac-signature) on the community forum that discussed the particular HMAC requirements for the REST endpoints used with no clear answer.

I think a collect header starting with ```C.Crypto.createHmac('SHA1', `${C.Time.strftime(new Date().getTime()/1000, '%a, %d %b %Y %H:%M:%S %Z')}``` followed by the rest of the multi-line payload would probably work, but I'm unsure how to make sure the HTTP Date: header sent by Cribl matches exactly to that same value... can it also be assigned in the headers with some variable like {latest}?

Thanks!

**Comment by grimmthetallest** [comment]
Docs for the API endpoints and HMAC requirements are at https://duo.com/docs/adminapi

**Comment by bdalpe** [comment]
This feature is being tracked internally by CRIBL-9726. Setting this ticket as blocked.

**Comment by bdalpe** [comment]
This is now unblocked with the release of Cribl 4.8: https://docs.cribl.io/stream/hmac-functions/
